const selectedChannels: string[] = [
    "Мир Премиум HD",
    "НТВ HD",
    "Первый канал HD",
    "РЕН ТB HD",
    "Россия HD",
    "Animal Planet HD",
    "Discovery Channel HD",
    "Discovery Science HD",
    "DocuBox HD",
    "HD Life",
    "History 2 HD",
    "History Channel HD",
    "Mute HD",
    "Nat Geo Wild HD",
    "National Geographic HD",
    "Ocean TV HD",
    "RTG HD",
    "Russia Today Doc HD",
    "Sochi Live HD",
    "TLC HD",
    "Travel + adventure HD",
    "Travel Channel HD",
    "TSTV HD",
    "Viasat Nature-History HD",
    "В мире животных HD",
    "Загорoдный HD",
    "Загородный International HD",
    "Министерство идей HD",
    "Нано ТВ",
    "Наука",
    "Наука 2.0",
    "Наша Сибирь HD",
    "Парк Патриот HD",
    "Планета HD",
    "Приключения HD",
    "HD Media",
    "Paramount Comedy",
    "Red Bull TV HD",
    "RTSH1 HD",
    "RTSH3 HD",
    "Star Family HD",
    "Пятница",
    "Пятница (+2)",
    "Пятница International",
    "СТС",
    "СТС (+2)",
    "СТС International",
    "СТС Love",
    "СТС Балтия",
    "ТНТ",
    "ТНТ (+2)",
    "ТНТ (+4)",
    "ТНТ HD",
    "ТНТ4",
    "ТНТ4 (+2)",
    "CBS News HD",
    "CNN International",
    "News One HD",
    "Russia Today HD",
    "Sky News HD",
    "Times Now HD",
    "Дождь HD",
    "Известия HD",
    "Мир 24 HD",
    "Россия 24",
    "Amedia Hit HD",
    "Amedia Premium HD",
    "Epic Drama HD",
    "Fliх HD",
    "Fox HD",
    "Fox Life HD",
    "MGM HD",
    "Rai Movie HD",
    "Rai Premium HD",
    "SET HD",
    "Spike HD",
    "TV 1000 Actiоn HD",
    "ViP Comedy HD",
    "ViP Megahit HD",
    "ViP Premiere HD",
    "Дом кино Премиум HD",
    "Кино ТВ HD",
    "Киноменю HD",
    "КиноПремиум HD",
    "премьера HD",
    "Наш детектив HD",
    "Наш кинороман HD",
    "Остросюжетное HD",
    "Русский роман HD",
    "Синамо ТВ HD",
    "AD Sport 1 HD",
    "AD Sport 2 HD",
    "CBC Sport HD",
    "Eurosport 1 HD",
    "Eurosport 2 HD",
    "FightBox HD",
    "MostVideo.TV HD",
    "Nautical Channel HD",
    "Olympic Channel HD",
    "Super Tennis HD",
    "TVP Sport HD",
    "Viasat Sport HD",
    "Матч ТВ HD",
    "Матч! Арена HD",
    "Матч! Игра HD",
    "Матч! Футбол 1 HD",
    "Матч! Футбол 1 HD Резерв 1",
    "Матч! Футбол 1 HD Резерв 2",
    "Матч! Футбол 1 HD Резерв 3",
    "Матч! Футбол 2 HD",
    "Матч! Футбол 3 HD",
    "Моторспорт ТВ HD",
    "Футбoл HD",
    "Футбол 1 HD",
    "Футбол 2 HD",
    "Русский экстрим HD",
    "Gurinel TV HD",
    "Nickelodeon HD",
    "Мультик HD",
    "Рыжий HD",
    "Смайлик ТВ HD",
    "Тлум HD",
    "0x0 Music HD",
    "1 HD",
    "Bridge HD",
    "Classic Arts Showcase HD",
    "Clik TV HD",
    "EU Music HD",
    "Extrema TV HD",
    "MTV Live HD",
    "MTV Россия HD",
    "Music Box RU HD",
    "PortalFoxMix HD",
    "RJTV HD",
    "RU TV HD",
    "VIVA Russia HD",
    "Первый музыкальный HD",
    "Первый музыкальный Россия HD",
];

const selectedChannelsSet = new Set(selectedChannels);

export {
    selectedChannels,
    selectedChannelsSet,
}
